#!/usr/bin/env npx tsx
/**
 * SOC 2 validation orchestrator — runs the /soc2-validate suite from CLAUDE.md.
 * Location: scripts/compliance/run-validate-soc2.ts
 * Usage: npm run validate:soc2 [-- --skip-db] [-- --with-tests]
 */

import { execSync } from 'child_process';
import { existsSync, mkdirSync, writeFileSync, readdirSync, readFileSync } from 'fs';
import { join } from 'path';

const ROOT = process.cwd();
const skipDb = process.argv.includes('--skip-db');
const withTests = process.argv.includes('--with-tests') || !process.argv.includes('--no-tests');

interface StepResult {
  name: string;
  command: string;
  exitCode: number;
  ok: boolean;
  note?: string;
}

function runStep(name: string, command: string, allowFail = false): StepResult {
  console.log(`\n▶ ${name}\n  $ ${command}\n`);
  try {
    execSync(command, { cwd: ROOT, stdio: 'inherit', env: process.env });
    return { name, command, exitCode: 0, ok: true };
  } catch (e: unknown) {
    const code = (e as { status?: number }).status ?? 1;
    if (allowFail) {
      console.warn(`⚠ ${name} exited ${code} (allowed)`);
      return { name, command, exitCode: code, ok: false, note: 'allowed-fail' };
    }
    console.error(`✗ ${name} failed with exit ${code}`);
    return { name, command, exitCode: code, ok: false };
  }
}

function loadEnv(): void {
  for (const file of ['.env.local', '.env']) {
    const path = join(ROOT, file);
    if (!existsSync(path)) continue;
    const text = readFileSync(path, 'utf8');
    for (const line of text.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const idx = trimmed.indexOf('=');
      if (idx <= 0) continue;
      const key = trimmed.slice(0, idx).trim();
      const value = trimmed.slice(idx + 1).trim().replace(/^["']|["']$/g, '');
      if (!(key in process.env)) process.env[key] = value;
    }
  }
}

loadEnv();

const steps: StepResult[] = [];

steps.push(runStep('Security preflight', 'npm run security:preflight', true));

const policyCmd = withTests
  ? 'npx tsx scripts/compliance/validate-policy-implementation.ts --with-tests'
  : 'npx tsx scripts/compliance/validate-policy-implementation.ts';
steps.push(runStep('Policy runtime anchors', policyCmd, true));

if (process.env.DATABASE_URL && !skipDb) {
  steps.push(runStep('pgAudit verify', 'npx tsx scripts/compliance/verify-pgaudit.ts --json', true));
  steps.push(runStep('Tenant RLS', 'npx tsx scripts/db/verify-tenant-rls.ts', true));
  steps.push(runStep('DB migrations', 'npm run test:db:migrations', true));
  steps.push(runStep('SOC2 collect-evidence', 'npx tsx scripts/soc2/collect-evidence.ts', true));
} else {
  console.warn('\n⚠ DATABASE_URL not set — skipping DB-backed steps (use --skip-db to silence)\n');
}

const failed = steps.filter((s) => !s.ok && s.note !== 'allowed-fail');
const allowedWarn = steps.filter((s) => !s.ok && s.note === 'allowed-fail');

const month = new Date().toISOString().slice(0, 7);
const outDir = join(ROOT, 'compliance/evidence/policies');
mkdirSync(outDir, { recursive: true });

let latestSoc2: string | null = null;
const soc2Dir = join(ROOT, 'compliance/evidence/soc2');
if (existsSync(soc2Dir)) {
  const files = readdirSync(soc2Dir)
    .filter((f) => f.startsWith('soc2_audit_') && f.endsWith('.json'))
    .sort();
  latestSoc2 = files.at(-1) ?? null;
}

const reportPath = join(
  outDir,
  `IMPLEMENTATION_VALIDATION_${new Date().toISOString().slice(0, 10)}.md`
);

const md = `# Policy implementation validation — ${new Date().toISOString().slice(0, 10)}

**Orchestrator:** \`npm run validate:soc2\`  
**Matrix:** [POLICY_IMPLEMENTATION_MATRIX.md](POLICY_IMPLEMENTATION_MATRIX.md)

## Step results

| Step | Exit | Status |
|------|------|--------|
${steps.map((s) => `| ${s.name} | ${s.exitCode} | ${s.ok ? 'OK' : s.note === 'allowed-fail' ? 'WARN' : 'FAIL'} |`).join('\n')}

## SOC 2 agent JSON

${latestSoc2 ? `Latest: \`compliance/evidence/soc2/${latestSoc2}\`` : '_Not collected (DATABASE_URL missing or collect-evidence failed)_'}

## Summary

- Hard failures: ${failed.length}
- Allowed warnings: ${allowedWarn.length}
- Re-run: \`npm run validate:soc2\` from \`hotel-etuna/\`

## Open IMP gaps (see TASK.md)

| ID | Item | Owner |
|----|------|-------|
| IMP-01 | pgAudit on Neon | Dev — **compensating controls** via \`npm run verify:pgaudit\` (no Neon ticket required) |
| IMP-03 | Executive policy signatures | CEO/CTO |
| IMP-04 | Platform MFA (Vercel/GitHub/Neon) | CTO |
| IMP-05 | Vendor SOC attestations | CTO |
| IMP-06 | Retention cron production dry-run evidence | Dev |

---

_Generated by scripts/compliance/run-validate-soc2.ts_
`;

writeFileSync(reportPath, md);
console.log(`\nWrote ${reportPath}`);

process.exit(failed.length > 0 ? 1 : 0);
